[project]
anchor_version = "0.31.1"

[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gorbadome = "5Qewhf89dYVr16QF9hW34PvTUDmvxHpZWHE3y19crbss"

[programs.devnet]
gorbadome = "5Qewhf89dYVr16QF9hW34PvTUDmvxHpZWHE3y19crbss"

[programs.mainnet]
gorbadome = "5Qewhf89dYVr16QF9hW34PvTUDmvxHpZWHE3y19crbss"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Gorganus Chain Configuration
[cluster.gorganus-devnet]
url = "https://rpc.gorganus.com"
ws_url = "wss://rpc.gorganus.com"

[cluster.gorganus-mainnet]
url = "https://mainnet-rpc.gorganus.com"
ws_url = "wss://mainnet-rpc.gorganus.com"
